version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: runalytics-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-runalytics}
      POSTGRES_USER: ${POSTGRES_USER:-runalytics}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-runalytics}
    ports:
      - "5433:5432"
    volumes:
      - runalytics_db:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-runalytics} -d ${POSTGRES_DB:-runalytics}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: runalytics-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Dans le réseau docker, l’hôte DB est "postgres"
      DATABASE_URL: postgresql://${POSTGRES_USER:-runalytics}:${POSTGRES_PASSWORD:-runalytics}@postgres:5432/${POSTGRES_DB:-runalytics}?schema=public
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      # volume anonyme pour ne pas écraser node_modules par le bind mount
      - /usr/src/app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"

volumes:
  runalytics_db:
